version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-fun-bot
    env_file:
      - .env
    ports:
      - "${BOT_PORT:-31999}:${BOT_PORT:-31999}"
    restart: unless-stopped