blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Support
    url: https://discord.gg/your-server
    about: Get help from the community
  - name: 📖 Documentation
    url: https://github.com/M1XZG/discord-bot-for-fun/tree/main/docs
    about: Check our documentation first
  - name: 🤔 Discussions
    url: https://github.com/M1XZG/discord-bot-for-fun/discussions
    about: For questions and general discussions